name: PHPUnit for Hyperf

on: [push, pull_request]

env:
  SW_VERSION: 'develop'

jobs:
  ci:
    name: Test on PHP ${{ matrix.php-version }}
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: ['7.3', '7.4']
      max-parallel: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: extension=swow, opcache.enable_cli=1
          coverage: none
      - name: Setup Devtool
        run: |
          sudo apt-get install -y valgrind
      - name: Setup Swow
        run: |
          wget https://github.com/swow/swow/archive/"${SW_VERSION}".tar.gz -O swow.tar.gz
          mkdir -p swow
          tar -xf swow.tar.gz -C swow --strip-components=1
          rm swow.tar.gz
          cd swow/ext || exit
          phpize
          ./configure --enable-debug
          make -j "$(nproc)"
          sudo make install
      - name: Setup Packages
        run: composer update -o
      - name: Run Test Cases
        run: |
          composer analyse
          composer test
